-- Trigger for automated replication
CREATE OR REPLACE TRIGGER trg_replicate_to_db2
AFTER INSERT OR UPDATE OR DELETE ON EMPLOYEES
FOR EACH ROW
BEGIN
    -- INSERT/UPDATE replication
    IF INSERTING OR UPDATING THEN
        MERGE INTO EMPLOYEES@db2 d
        USING (SELECT :NEW.EMP_ID AS EMP_ID, :NEW.NAME AS NAME, :NEW.POSITION AS POSITION, :NEW.SALARY AS SALARY FROM DUAL) s
        ON (d.EMP_ID = s.EMP_ID)
        WHEN MATCHED THEN
            UPDATE SET d.NAME = s.NAME, d.POSITION = s.POSITION, d.SALARY = s.SALARY
        WHEN NOT MATCHED THEN
            INSERT (EMP_ID, NAME, POSITION, SALARY) VALUES (s.EMP_ID, s.NAME, s.POSITION, s.SALARY);
    END IF;

    -- DELETE replication
    IF DELETING THEN
        DELETE FROM EMPLOYEES@db2 WHERE EMP_ID = :OLD.EMP_ID;
    END IF;
END;
/