-- Create database link
CREATE DATABASE LINK db2
CONNECT TO studentid IDENTIFIED BY "password"
USING '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=oracle12c.scs.ryerson.ca)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=orcl12c)))';

-- Insert initial data
INSERT INTO EMPLOYEES (EMP_ID, NAME, POSITION, SALARY) VALUES (1, 'Ekrem Yilmaz', 'Manager', 75000);
INSERT INTO EMPLOYEES (EMP_ID, NAME, POSITION, SALARY) VALUES (2, 'Hasan Ercikdi', 'Developer', 60000);
INSERT INTO EMPLOYEES (EMP_ID, NAME, POSITION, SALARY) VALUES (3, 'Ramazan Ercikdi', 'Analyst', 55000);

-- Insert additional data
INSERT INTO EMPLOYEES (EMP_ID, NAME, POSITION, SALARY) VALUES (4, 'John Doe', 'Security', 50000);
INSERT INTO EMPLOYEES (EMP_ID, NAME, POSITION, SALARY) VALUES (5, 'Jane Smith', 'Developer', 60000);
INSERT INTO EMPLOYEES (EMP_ID, NAME, POSITION, SALARY) VALUES (6, 'Alice Johnson', 'Treasurer', 55000);

-- Update and delete operations
UPDATE EMPLOYEES SET SALARY = 5000 WHERE EMP_ID = 5;
DELETE FROM EMPLOYEES WHERE EMP_ID = 5;

-- Verify replication
SELECT * FROM EMPLOYEES; -- Oracle 11g
SELECT * FROM EMPLOYEES@db2; -- Oracle 12c