-- SYNC_LOG table and sequence
CREATE TABLE SYNC_LOG (
    LOG_ID NUMBER PRIMARY KEY,
    SYNC_TIMESTAMP TIMESTAMP DEFAULT SYSTIMESTAMP,
    OPERATION_TYPE VARCHAR2(10),
    EMP_ID NUMBER
);

CREATE SEQUENCE SYNC_LOG_SEQ START WITH 1 INCREMENT BY 1;