-- Stored procedure for synchronization
CREATE OR REPLACE PROCEDURE sync_employees_to_db2 AS
BEGIN
    -- Insert new rows
    INSERT INTO EMPLOYEES@db2 (EMP_ID, NAME, POSITION, SALARY)
    SELECT EMP_ID, NAME, POSITION, SALARY
    FROM EMPLOYEES
    WHERE EMP_ID NOT IN (SELECT EMP_ID FROM EMPLOYEES@db2);

    -- Update existing rows
    MERGE INTO EMPLOYEES@db2 d
    USING (SELECT EMP_ID, NAME, POSITION, SALARY FROM EMPLOYEES) s
    ON (d.EMP_ID = s.EMP_ID)
    WHEN MATCHED THEN
        UPDATE SET d.NAME = s.NAME, d.POSITION = s.POSITION, d.SALARY = s.SALARY;

    -- Delete orphaned rows
    DELETE FROM EMPLOYEES@db2
    WHERE EMP_ID NOT IN (SELECT EMP_ID FROM EMPLOYEES);

    COMMIT;
END;
/